config:
    #norm: -1 # default
    norm: 1   # LDAM
model:
    feature_extractor:
        arch: resnet50
    classifier:
        arch: linearcls
        feat_size: 2048
        n_class: 345
        norm: 1
data:
    loader: BaseDataLoader
    data_root: /data8/gina/dataset/DomainNet
    train: /data8/gina/dataset/DomainNet/sketch_train.txt
    val: /data8/gina/dataset/DomainNet/sketch_test.txt
    n_workers: 4
checkpoint: runs/ldam/clipart/ep-200_model.pkl
logfile: runs/ldam/clipart/test_sketch_result.log
outfile: runs/ldam/clipart/test_sketch.json
