seed: 1
model:
    feature_extractor:
        arch: resnet50
        pretrained: true
    classifier:
        arch: mlpcls
        nonlinear: relu
        feat_size: [2048, 256] # [feat_dim, bottleneck_dim]
        n_class: 31 # domainnet
    discriminator:
        arch: advnet
        in_feature: 256 # bottleneck_dim x n_class (if not using random layer)
        hidden_size: 1024
data:
    source:
        loader: JSONDataLoader
        data_root: /data/
        n_workers: 4
        drop_last: true
        ann: true
        loc: false
        meta: false
    target:
        loader: JSONDataLoader
        data_root: /data/
        n_workers: 4
        drop_last: true
        ann: false ## UDA
        loc: false
        meta: false
training:
    trainer: cdan
    losses:
        loss_cls:
            name: cross_entropy
        loss_d:
            name: cdan
            use_entropy: false # true for CDAN+E; false for CDAN
            coeff: 1
    iteration: 100004
    batch_size: 32
    # batch_size: 256
    val_interval: 5000
    save_interval: 5000
    print_interval: 2500
    optimizer:
        name: sgd
        # lr: 0.03
        momentum: 0.9
        weight_decay: 0.0005
        nesterov: false
    scheduler:
        init_lr: 0.003
        name: inv
        gamma: 0.001
        power: 0.75
    # scheduler:
    #     name: multiStepLr
    #     gamma: 0.1
    #     milestones: [35000,50000,60000]
    resume:
        #model: runs/plain/clipart/ep-200_model.pkl
        model: 
        load_cls: false
        param_only: true
exp: a2d_noldam
