seed: 1
model:
    feature_extractor:
        arch: resnet50
        pretrained: true
    classifier:
        arch: mlpcls
        nonlinear: relu
        # norm: 1 # LDAM
        feat_size: [2048, 256] # [feat_dim, bottleneck_dim]
        # feat_size: 2048 # [feat_dim, bottleneck_dim]
        n_class: 31 # domainnet
data:
    source:
        loader: FileDataLoader
        data_root: /data/
        train: source.txt
        val: source.txt
        n_workers: 16
        drop_last: true
        n_class: 31 # domainnet
        sampler:
            name: random
        imbalance_factor: 1
        reversed: false
        mode: exp
        inverse: false
    target:
        loader: FileDataLoader
        data_root: /data/
        train: target.txt
        val: target.txt
        n_workers: 16
        drop_last: true
        n_class: 31 # domainnet
        sampler:
            name: random
        imbalance_factor: 1
        reversed: false
        mode: exp
        inverse: false
training:
    trainer: plain
    losses:
        loss_cls:
            name: cross_entropy
    iteration: 100004
    # batch_size: 32
    batch_size: 256
    val_interval: 5000
    save_interval: 10000
    print_interval: 2500
    optimizer:
        name: sgd
        momentum: 0.9
        weight_decay: 0.0005
        nesterov: true
    # scheduler:
    #     init_lr: 0.003
    #     name: inv
    #     gamma: 0.001
    #     power: 0.75
    scheduler:
        init_lr: 0.001
        name: multiStepLr
        gamma: 0.1
        milestones: [10000,20000,30000]
    resume:
        #model: runs/plain/clipart/ep-200_model.pkl
        model: 
        load_cls: false
        param_only: true
exp: a2d_noldam
