seed: 1
model:
    feature_extractor:
        arch: resnet50
        pretrained: false
    classifier:
        arch: mlpcls
        nonlinear: relu
        feat_size: [2048, 256] # [feat_dim, bottleneck_dim]
        n_class: 31 # domainnet
data:
    target:
        loader: JSONDataLoader
        data_root: /data/
        n_workers: 4
        drop_last: true
        ann: false ## UDA
        loc: false
        meta: false
testing:
    batch_size: 64
    resume:
        model: 
        load_cls: true
        param_only: true
exp: a2d_noldam
